
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const isGenerateCommand = process.argv.includes("generate");
const generateOnlyUrl = "postgresql://generated:generated@127.0.0.1:5432/generated";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: isGenerateCommand
      ? process.env.DATABASE_URL ?? generateOnlyUrl
      : env("DATABASE_URL"),
    directUrl: env("DIRECT_URL"),
  },
});
